# /opt/docker-compose.yml
---
version: '2'
services:
        #adguard:
        #        container_name: adguard
        #        image: adguard/adguardhome:latest
        #        ports:
        #          - "53:53/tcp"
        #          - "53:53/udp"
        #          - "67:67/udp"
        #          - "68:68/udp"
        #          - "8240:8240/tcp"
        #          - "3000:3000/tcp"
        #          - "853:853/tcp"
        #        environment:
        #        - TZ=Europe/London
        #        - LETSENCRYPT_HOST=adguard.thechurchills.org.uk
        #        - LETSENCRYPT_EMAIL:terry@thechurchills.org.uk
        #        - VIRTUAL_HOST=adguard.thechurchills.org.uk
        #        - VIRTUAL_PORT="8240"
        #        # Volumes store your data between container upgrades
        #        volumes:
        #        - /dockerfiles/adguard/workdir:/opt/adguardhome/work
        #        - /dockerfiles/adguard/confdir:/opt/adguardhome/conf
        #        network_mode: "bridge"
        #        restart: always
        docker-proxy:
                image: jwilder/nginx-proxy:latest
                container_name: docker-proxy
                volumes:
                - /dockerfiles/ssl-certs:/etc/nginx/certs
                - /dockerfiles/nginx-proxy/:/etc/nginx/vhost.d/
                - /var/run/docker.sock:/tmp/docker.sock
                - /etc/nginx/vhost.d
                - /usr/share/nginx/html
                restart: always
                ports:
                - 80:80
                - 443:443
                network_mode: "bridge"
        docker-proxy-sslgen:
                image: jrcs/letsencrypt-nginx-proxy-companion
                container_name: docker-proxy-sslgen
                depends_on:
                - docker-proxy
                volumes:
                - /var/run/docker.sock:/var/run/docker.sock:ro
                volumes_from:
                - docker-proxy:rw
                network_mode: "bridge"
                restart: always
        nzbhydra:
                image: linuxserver/nzbhydra2
                container_name: nzbhydra
                volumes:
                - /dockerfiles/nzbhydra:/config
                - /etc/localtime:/etc/localtime:ro
                  #- /etc/hosts:/etc/hosts
                restart: always
                ports:
                - 5076:5076
                environment:
                - PGID=501
                - PUID=501
                - LETSENCRYPT_HOST=nzbhydra.thechurchills.org.uk
                - LETSENCRYPT_EMAIL=terry@thechurchills.org.uk
                - VIRTUAL_HOST=nzbhydra.thechurchills.org.uk
                - TZ=Europe/London
                network_mode: "bridge"
        nzbget:
                image: linuxserver/nzbget
                container_name: nzbget
                volumes:
                - /dockerfiles/nzbget:/config
                - /home/terry/downloads/:/downloads
                  #- /dockerfiles/nzbtemp/:/intermediate
                - /mnt/scratch/nzbgettmp/:/intermediate
                - /dockerfiles/nzbgetscripts:/scripts
                restart: always
                ports:
                - 6789:6789
                environment:
                - PGID=501
                - PUID=501
                - LETSENCRYPT_HOST=nzbget.thechurchills.org.uk
                - LETSENCRYPT_EMAIL=terry@thechurchills.org.uk
                - VIRTUAL_HOST=nzbget.thechurchills.org.uk
                - TZ=Europe/London
                network_mode: "bridge"
        radarr:
                image: linuxserver/radarr:nightly
                container_name: radarr
                volumes:
                - /home/terry/downloads:/done
                - /dockerfiles/radarr:/config
                - /home/terry/downloads:/downloads
                - /mnt/Media/Movies:/movies
                - /dev/rtc:/dev/rtc:ro
                restart: always
                ports:
                - 5050:7878
                environment:
                - PGID=501
                - PUID=501
                - LETSENCRYPT_HOST=radarr.thechurchills.org.uk
                - LETSENCRYPT_EMAIL=terry@thechurchills.org.uk
                - VIRTUAL_HOST=radarr.thechurchills.org.uk
                - TZ=Europe/London
                network_mode: "bridge"
        sonarr:
                image: lsiodev/sonarr:latest
                container_name: sonarr
                volumes:
                - /home/terry/downloads:/done
                - /dockerfiles/sonarr:/config
                - /home/terry/downloads:/downloads
                - /mnt/Media/TV:/tv
                - /dev/rtc:/dev/rtc:ro
                restart: always
                ports:
                - 8989:8989
                environment:
                - PGID=501
                - PUID=501
                - LETSENCRYPT_HOST=sonarr.thechurchills.org.uk
                - LETSENCRYPT_EMAIL=terry@thechurchills.org.uk
                - VIRTUAL_HOST=sonarr.thechurchills.org.uk
                - TZ=Europe/London
                network_mode: "bridge"
        embyserver:
                image: emby/embyserver
                container_name: embyserver
                volumes:
                - /dockerfiles/emby/config:/config
                - /dockerfiles/embyusb/cache:/config/cache
                - /dockerfiles/embyusb/data:/config/data
                - /mnt/Media/TV:/mnt/tv
                - /mnt/Media/Movies:/mnt/movies
                - /mnt/RAID/Photos:/mnt/photos
                - /mnt/RAID/recordings:/mnt/youtube
                - /mnt/RAID/Movies4k:/mnt/Movies4K
                - /dockerfiles/emby-sync:/mnt/emby-sync
                - /dockerfiles/emby-backup/:/backup
                - /mnt/RAID/emby-prerolls/:/preroll
                devices:
                - "/dev/dri/renderD128"
                ports:
                - 8096:8096
                - 8920:8920
                environment:
                - UID=501
                - GID=501
                - GIDLIST=44,501
                network_mode: "host"
                restart: always
       #mariadb:
       #         image: mariadb:latest
       #         container_name: mariadb
       #         volumes:
       #         - /dockerfiles/mariadb:/var/lib/mysql
       #         ports:
       #         - 3306:3306
       #         environment:
       #         - PUID=501
       #         - PGID=501
       #         - TZ=Europe/London
       #         network_mode: "host"
       #         restart: always
       #portainer:
                #image: portainer/portainer-ce
                #container_name: portainer
                #volumes:
                #- /dockerfiles/portainer/:/data
                #- /var/run/docker.sock:/var/run/docker.sock
                #environment:
                #- LETSENCRYPT_HOST=portainer.thechurchills.org.uk
                #- LETSENCRYPT_EMAIL=terry@thechurchills.org.uk
                #- VIRTUAL_HOST=portainer.thechurchills.org.uk
                #- VIRTUAL_PORT="9000"
                #network_mode: "host"
                #restart: always
        apps:
                image: linuxserver/heimdall:latest
                container_name: apps
                volumes:
                - /etc/localtime:/etc/localtime:ro
                - /dockerfiles/heimdall:/config
                - /etc/hosts:/etc/hosts
                ports:
                  - 8095:80
                environment:
                - PUID=501
                - PGID=501
                - TZ=Europe/London
                - LETSENCRYPT_HOST=apps.thechurchills.org.uk
                - LETSENCRYPT_EMAIL=terry@thechurchills.org.uk
                - VIRTUAL_HOST=apps.thechurchills.org.uk
                network_mode: "bridge"
                restart: always
        traktarr:
                container_name: traktarr
                image: eafxx/traktarr:latest
                volumes:
                    - /dockerfiles/traktarr:/config
                environment:
                - PUID=501
                - PGID=501
                - TZ=Europe/London
                - DELAY=5
                - SORT=rating
                - NOSEARCH=yes
                - NOTIFICATIONS=yes
                - BLACKLIST=yes
                - RUNNOW=yes
                - SKIPUPDATE=no
                - APP_BRANCH=develop
                network_mode: "bridge"
                restart: always
        smokeping:
                image: linuxserver/smokeping
                container_name: smokeping
                volumes:
                - /dockerfiles/smokeping/data:/data
                - /dockerfiles/smokeping/config:/config
                ports:
                  - 6556:80
                environment:
                - PUID=501
                - PGID=501
                - TZ=Europe/London
                - LETSENCRYPT_HOST=smokeping.thechurchills.org.uk
                - LETSENCRYPT_EMAIL=terry@thechurchills.org.uk
                - VIRTUAL_HOST=smokeping.thechurchills.org.uk
                network_mode: "bridge"
                restart: always
                #radarr4k:
                #image: linuxserver/radarr:nightly
                #container_name: radarr4k
                #volumes:
                #- /home/terry/downloads:/done
                #- /dockerfiles/radarr4k:/config
                #- /home/terry/downloads:/downloads
                #- /mnt/RAID/Movies4k:/movies
                #- /dev/rtc:/dev/rtc:ro
                #restart: always
                #ports:
                #- 5051:7878
                #environment:
                #- PGID=501
                #- PUID=501
                #- LETSENCRYPT_HOST=radarr4k.thechurchills.org.uk
                #- LETSENCRYPT_EMAIL=terry@thechurchills.org.uk
                #- VIRTUAL_HOST=radarr4k.thechurchills.org.uk
                #- TZ=Europe/London
                #network_mode: "bridge"
        speedtest:
                container_name: speedtest
                image: henrywhitaker3/speedtest-tracker
                ports:
                - 8765:80
                volumes:
                - /dockerfiles/speedtest:/config
                environment:
                - TZ=Europe/London
                - PGID=501
                - PUID=501
                - OOKLA_EULA_GDPR=true
                - VIRTUAL_HOST=speedtest.thechurchills.org.uk
                logging:
                    driver: "json-file"
                    options:
                        max-file: "10"
                        max-size: "200k"
                network_mode: "bridge"
        dozzle:
               container_name: dozzle
               image: amir20/dozzle:latest
               volumes:
               - /var/run/docker.sock:/var/run/docker.sock
               environment:
               - VIRTUAL_HOST=logs.thechurchills.org.uk
               ports:
               - 8888:8080
               network_mode: "bridge"
        ombi:
               container_name: ombi
               image: ghcr.io/linuxserver/ombi
               volumes:
               - /dockerfiles/ombi:/config
               environment:
               - PUID=501
               - PGID=501
               - TZ=Europe/London
               - VIRTUAL_HOST=ombi.thechurchills.org.uk
               ports:
               - 3579:3579
               network_mode: "bridge"
