# /opt/docker-compose.yml
---
version: '2'
services:
        mariadb:
                image: mariadb:latest
                container_name: mariadb
                volumes:
                - /dockerfiles/mariadb:/var/lib/mysql
                ports:
                - 3306:3306
                environment:
                - PUID=501
                - PGID=501
                - TZ=Europe/London
                network_mode: "host"
