# /opt/docker-compose.yml
---
version: '2'
services:
        vpn:
                image: linuxserver/openvpn-as
                container_name: docker-proxy
                volumes:
                - /dockerfiles/openvpn-as:/config
                restart: always
                privileged: true
                environment:
                - PGID=501
                - PGID=501
                - PUID=501
                - TZ=Europe/London
                - INTERFACE=br0
                network_mode: "host"
