# /opt/docker-compose.yml
---
version: '2'
services:
        vpn:
                image: linuxserver/openvpn-as
                container_name: openvpn-as
                volumes:
                - /dockerfiles/openvpn-as:/config
                restart: always
                privileged: true
                environment:
                - PGID=501
                - PUID=501
                - TZ=Europe/London
                - INTERFACE=br0
                network_mode: "host"
        plex:
                image: linuxserver/plex
                container_name: plex
                volumes:
                - /dockerfiles/plex:/config
                - /mnt/RAID/TV:/data/tvshows
                - /mnt/RAID/Music:/data/music
                - /mnt/RAID/Movies:/data/movies
                - /mnt/RAID/Movies4K:/data/movies4K
                - /home/terry/plex-transcode:/transcode
                restart: always
                privileged: true
                environment:
                - VERSION=latest
                - PUID=501
                - PGID=501
                - TZ=Europe/London
                network_mode: "host"
        mariadb:
                image: mariadb:latest
                container_name: mariadb
                volumes:
                - /dockerfiles/mariadb:/var/lib/mysql
                ports:
                - 3306:3306
                environment:
                - PUID=501
                - PGID=501
                - TZ=Europe/London
                network_mode: "host"
